### PR TITLE
fix: check env when url or token is not provided

### PR DESCRIPTION
**Pull request by avnigenc**

### CODE REVIEW

**Comment by chronark** [comment]
Hey @avnigenc, thanks for contributing! Could you briefly describe your motivation for this change?

**Comment by avnigenc** [comment]
Hi @chronark , The main reason for this change is to increase the developer experience. The developer may forget to set the URL and token or may have had problems reading the customized `.env` file. In these cases, if the environment variables already have Redis URL and token, I thought it would be a good practice to try to read from there.

**Comment by chronark** [comment]
@avnigenc I see
but why wouldn't you just use the `fromEnv()` in the first place?
Also typescript will not allow passing in undefined, so that should not happen by accident

**Comment by chronark** [comment]
Closing this due to inactivity

**Pull request closed without merging**
